language: java
env:
        - JEP_HOME="$(python -m site --user-site)/jep"
        - ROUGE_HOME="./ROUGE-1.5.5/RELEASE-1.5.5"
before_install:
        - (echo y;echo o conf prerequisites_policy follow;echo o conf commit) | sudo cpan install XML::DOM
        - ./rouge_install.sh
        - sudo apt-get install -y glpk-utils
        - pip install gensim --user
        - pip install jep --user
        - source jep_env_before
after_install:
        - source jep_env_after
