language: java
dist: "trusty"
env:
    global:
        - JEP_HOME="$(python3 -m site --user-site)/jep"
        - ROUGE_HOME="./ROUGE-1.5.5/RELEASE-1.5.5"
before_install:
        - sudo apt-get update
        - sudo apt-get install -y python3
        - sudo apt-get install -y python3-pip
        - sudo apt-get install -y glpk-utils
        - (echo y;echo o conf prerequisites_policy follow;echo o conf commit) | sudo cpan install XML::DOM >> cpan_log
        - ./rouge_install.sh
        - pip3 install gensim --user >> gensim_log
        - pip3 install jep --user
        - source jep_env_before
after_install:
        - source jep_env_after
