language: java
env:
        - JEP_HOME="$(python -m site --user-site)/jep"
before_install:
        - sudo apt-get install -y glpk-utils
        - pip install gensim --user
        - pip install jep --user
        - ./jep_env_before.sh
after_install:
        - ./jep_env_after.sh
